# Generated by Django 4.2.7 on 2023-11-29 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChessGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_state', models.TextField(default='RNBQKBNRPPPPPPPP................................pppppppprnbqkbnr')),
                ('turn', models.CharField(default='W', max_length=1)),
                ('is_game_over', models.BooleanField(default=False)),
            ],
        ),
    ]
